spring:
  application:
    name: inbox-app
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Iv1.40885b6584723a72
            client-secret: 5c666dc1a0c566e7e330e70a29e8d71cd996e8c3

  data:
    cassandra:
      keyspace-name: main
      username: RJUDpwgalJnpNAqBZJUkQnNx
      password: PH9uLUFyP-+8oB,ItlADoQy-5nhnQvy4E1P2O+QZaJoH,,3eL.HrxmoTb4NwAF,S7YToaKSl4wh.ZIRh.I0DN-mJfaCA5pfrng5ZdsQWGJFPKTzIQlItl+QSsX0gwfez
      schema-action: recreate-drop-unused
      request:
        timeout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s

astra.db:
  id: 31b5847a-9b0b-49c2-8d29-2abb2dd069e7
  region: asia-south1
  keyspace: main
  application.token: AstraCS:RJUDpwgalJnpNAqBZJUkQnNx:5b79862658996efdce4ddd1109572ddddf26532324a228c7ef0b4b36738682d9

datastax.astra:
  secure-connect-bundle: secure-connect.zip
